name: pseudomonas-environment
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.9
  - ipykernel
  - pyani
  - ncbi-datasets-cli
  - raxml
  - r-devtools
  - pip:
    - jupyter
    - rpy2
