name: pseudomonas-environment
channels:
  - defaults
  - bioconda
  - conda-forge
  - r
dependencies:
  - ipykernel
  - pyani
  - ncbi-datasets-cli
  - raxml
  - r-devtools
  - r-pheatmap
  - pip:
    - jupyter
    - rpy2
